### ISSUE TITLE
WSS is required if -web is served over HTTPS

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick-discovery#2]
![image](https://user-images.githubusercontent.com/8290680/77240882-41267400-6c3f-11ea-87c6-53b84bf3c093.png)

**Comment by fnoop** [comment]
Hmm, this is a problem.  I guess we can make -discovery listen to a second fixed port with https, if certs available?

**Comment by SamuelDudley** [comment]
Yep. We can start a second server on another port from the same application.

**Comment by SamuelDudley** [comment]
https://github.com/tornadoweb/tornado/issues/523

The same codebase needs to attach two Tornado applications to the same ioloop. These applications are then served on two ports but share the same websocket handlers.
